version: '3'
services:
  web:
    build: .
    ports:
      - "127.0.0.1:80:80"
    networks:
      - mynetwork
  redis:
    image: "redis:alpine"
    networks:
      - mynetwork
    ports:
      - "127.0.0.1:6379:6379"

networks:
  mynetwork: